name: Auto-tag
on:
  push:
    branches:
      - main

jobs:
  # ... potentially other jobs ...
  terraform-provider-release:
    name: 'Terraform Provider Release'
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v4
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
      passphrase: ${{ secrets.PASSPHRASE }}
    with:
      setup-go-version-file: 'go.mod'
